/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("ReviewsObjectPageObjectPage journey");

        opaTest("Navigate to ReviewsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheCustomersList.onFilterBar().iExecuteSearch();

            Then.onTheCustomersList.onTable().iCheckRows();
            When.onTheCustomersList.onTable().iPressRow(0);

            Then.onTheCustomersObjectPage.iSeeThisPage();
            Then.onTheCustomersObjectPage.onTable({ property: "reviews" }).iCheckRows();
            When.onTheCustomersObjectPage.onTable({ property: "reviews" }).iPressRow(0);

            Then.onTheReviewsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheReviewsObjectPage.iCheckNumberOfSections(2);
            When.onTheReviewsObjectPage.iPressSectionIconTabFilterButton("Facet1");
            Then.onTheReviewsObjectPage.iCheckSection({ section: "Facet1" });
            When.onTheReviewsObjectPage.iPressSectionIconTabFilterButton("Facet2");
            Then.onTheReviewsObjectPage.iCheckSection({ section: "Facet2" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});